spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    password: admin
    url: jdbc:sqlite:D:\desktop\sxe\entity_with_service\sqlitesample.db
    username: admin

  jpa:
    database-platform: com.github.huifer.ews.persistence.SQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
